steps:
  - label: ":construction_worker: Build and push db"
    command: buildkite/db.sh

  - wait
  -
  - label: ":construction_worker: Build and push migrations"
    command: buildkite/migrations.sh
