#!/usr/bin/env bash
GIT_BRANCH=$(git -C "$PACKAGE_ROOT" symbolic-ref --short HEAD)
docker run --rm -d --network=host --name hint-db mrcide/hint-db:$GIT_BRANCH

# Need to give the database a little time to initialise before we can run the migration
docker exec hint-db wait-for-db
docker run --rm --network=host --name hint-db-migrate mrcide/hint-db-migrate:$GIT_BRANCH -url=jdbc:postgresql://localhost/hint
