#!/usr/bin/env bash
set -ex

HERE=$(dirname $0)

function cleardocker() {
  $HERE/clear-docker.sh
}
trap cleardocker EXIT



NETWORK=hint-db
DB=db

docker network create $NETWORK

docker run --rm -d \
  --network=$NETWORK \
  --name $DB \
  --network-alias db \
  -p 5432:5432 \
  $TAG_DB

# Need to give the database a little time to initialise before we can run the migrations
docker exec $DB wait-for-db
docker run --rm --network=$NETWORK \
  $TAG_MIGRATION \
  -url=jdbc:postgresql://$DB/hint
