name: Build Docker Image

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  TAG_DB_DH: mrcide/hint-db
  TAG_MIGRATION_DH: mrcide/hint-db-migrate
  TAG_DB_GHCR: hivtools/hint-db
  TAG_MIGRATION_GHCR: hivtools/hint-db-migrate

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: extract_branch
        name: Setup Environment
        shell: bash
        run: |
          if [ "${{github.event_name}}" = "pull_request" ];
          then
            LONG_SHA=${{ github.event.pull_request.head.sha }}
            echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            LONG_SHA=${GITHUB_SHA}
            echo "CI_BRANCH=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
          echo "CI_SHA=${LONG_SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev database container
        uses: docker/build-push-action@v6
        if: github.event_name == 'pull_request'
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: |
            ${{env.TAG_DB_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_DB_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Build and push database container
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: |
            ${{env.TAG_DB_DH}}:latest
            ${{env.TAG_DB_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_DB_GHCR}}:latest
            ghcr.io/${{env.TAG_DB_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Build dev migration container
        uses: docker/build-push-action@v6
        if: github.event_name == 'pull_request'
        with:
          context: migrations
          file: "./migrations/Dockerfile"
          load: true
          tags: |
            ${{env.TAG_MIGRATION_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Build prod migration container
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: migrations
          file: "./migrations/Dockerfile"
          load: true
          tags: |
            ${{env.TAG_MIGRATION_DH}}:latest
            ${{env.TAG_MIGRATION_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:latest
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Test migration container
        run: ./scripts/test_migrations
        env:
          GIT_ID: ${{steps.extract_branch.outputs.CI_BRANCH}}
          TAG_DB: ${{env.TAG_DB_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
          TAG_MIGRATION: ${{env.TAG_MIGRATION_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Push dev migration container
        uses: docker/build-push-action@v6
        if: github.event_name == 'pull_request'
        with:
          context: migrations
          file: "./migrations/Dockerfile"
          push: true
          tags: |
            ${{env.TAG_MIGRATION_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}

      - name: Push prod migration container
        uses: docker/build-push-action@v6
        if: github.event_name != 'pull_request'
        with:
          context: migrations
          file: "./migrations/Dockerfile"
          push: true
          tags: |
            ${{env.TAG_MIGRATION_DH}}:latest
            ${{env.TAG_MIGRATION_DH}}:${{steps.extract_branch.outputs.CI_BRANCH}}
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:latest
            ghcr.io/${{env.TAG_MIGRATION_GHCR}}:${{steps.extract_branch.outputs.CI_BRANCH}}
